---
schema: 1
name: WindowsFeature-enable-RDP
#enabled: false
tasks:
  - name: Enable Remote Desktop via registry
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
      name: fDenyTSConnections
      data: 0
      type: dword
      state: present
  - name: Enable Network Level Authentication (NLA)
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
      name: UserAuthentication
      data: 1
      type: dword
      state: present
  - name: Allow RDP through Windows Firewall
    community.windows.win_firewall_rule:
      name: Remote Desktop - User Mode (TCP-In)
      localport: 3389
      action: allow
      direction: in
      protocol: tcp
      state: present
      enabled: yes
  - name: Start Remote Desktop Services
    ansible.windows.win_service:
      name: TermService
      state: started
      start_mode: auto
