schema: 1
name: winsw-v2
source:
  - kind: github_release
    repo: winsw/winsw
    tag_regex: '^v2\..+$'
    asset_regex: '^WinSW-x64\.exe$'
    include_prereleases: false
    cache_filename: winsw-v2.exe
locked:
  - version: v2.12.0
    url: https://github.com/winsw/winsw/releases/download/v2.12.0/WinSW-x64.exe
    sha256: 05b82d46ad331cc16bdc00de5c6332c1ef818df8ceefcd49c726553209b3a0da
    cache_filename: winsw-v2.exe
tasks:
  - name: Create directory if it does not exist
    ansible.windows.win_file:
      path: "C:\\Tools\\WinSW\\v2"
      state: directory
  - name: Push the file to target device
    ansible.windows.win_copy:
      src: "{{ local_cache }}/winsw-v2.exe"
      dest: "C:\\Tools\\WinSW\\v2\\winsw.exe"
