schema: 1
name: neovim
cache_filename: nvim-win64.zip
source:
  kind: github_release
  repo: neovim/neovim
  tag_regex: '^v0\.12\.\d+$'
  asset_regex: '^nvim-win64\.zip$'
  include_prereleases: false
locked:
  version: v0.12.4
  url: https://github.com/neovim/neovim/releases/download/v0.12.4/nvim-win64.zip
  sha256: 9fc3572829ffd13debb6e32555da2c8cc02555568260a9fc4cf1f65bbcca319c
deploy:
  type: portable_zip
  destination: 'C:\Tools\Neovim'
  strip_single_root: true
  path: 'C:\Tools\Neovim\bin'
  add_to_path: true
