schema: 1
name: simple-http-server
cache_filename: simple-http-server.exe
source:
  kind: github_release
  repo: TheWaWaR/simple-http-server
  tag_regex: '^v\d+\.\d+\.\d+$'
  asset_regex: '^x86_64-pc-windows-msvc-simple-http-server\.exe$'
  include_prereleases: false
locked:
  version: v0.8.0
  url: https://github.com/TheWaWaR/simple-http-server/releases/download/v0.8.0/x86_64-pc-windows-msvc-simple-http-server.exe
  sha256: 6faac740df27e317125f562a4f5239fc2d95161aea995930929b1c895994aa9b
deploy:
  type: copy
  destination: 'C:\Tools\simple-http-server'
  target_filename: simple-http-server.exe
  path: 'C:\Tools\simple-http-server'
  add_to_path: true

